// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsqeqb1OE9pP8IP55Ta13ZZT2SZzNY54k',
    appId: '1:976214399132:web:2e1e4f1a97871a71643559',
    messagingSenderId: '976214399132',
    projectId: 'betterbee-eb5e8',
    authDomain: 'betterbee-eb5e8.firebaseapp.com',
    storageBucket: 'betterbee-eb5e8.appspot.com',
    measurementId: 'G-W40JSFY8W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf6Q9HZ2zx6bzX7LgObTUJ5tInsTJV8SU',
    appId: '1:976214399132:android:4391ecb1fb51cf12643559',
    messagingSenderId: '976214399132',
    projectId: 'betterbee-eb5e8',
    storageBucket: 'betterbee-eb5e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIAOmw62hVtykHO5KGg-hfia1QF-f3B9k',
    appId: '1:976214399132:ios:c31a0bfa3d19bbed643559',
    messagingSenderId: '976214399132',
    projectId: 'betterbee-eb5e8',
    storageBucket: 'betterbee-eb5e8.appspot.com',
    iosBundleId: 'com.betterlife.betterbee',
  );
}
